//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanaRequestInfo", Namespace="http://schemas.datacontract.org/2004/07/CBI.SANA.DataContracts")]
    public partial class SanaRequestInfo : object
    {
        
        private int AmountField;
        
        private int CurrencyIdField;
        
        private int CurrencyUseIdField;
        
        private string NationalIdField;
        
        private string TrackingCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyId
        {
            get
            {
                return this.CurrencyIdField;
            }
            set
            {
                this.CurrencyIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyUseId
        {
            get
            {
                return this.CurrencyUseIdField;
            }
            set
            {
                this.CurrencyUseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalId
        {
            get
            {
                return this.NationalIdField;
            }
            set
            {
                this.NationalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingCode
        {
            get
            {
                return this.TrackingCodeField;
            }
            set
            {
                this.TrackingCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanaBankInfo", Namespace="http://schemas.datacontract.org/2004/07/CBI.SANA.DataContracts")]
    public partial class SanaBankInfo : object
    {
        
        private int AmountField;
        
        private string BirthDateField;
        
        private int CurrencyCodeField;
        
        private string CurrencyNameField;
        
        private string CustomerIBANField;
        
        private string DealDateField;
        
        private string ExchangeNameField;
        
        private string ExchangeNationalIdField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MobileNumberField;
        
        private string NationalIdField;
        
        private decimal RialEqualityAmountField;
        
        private string ShIdField;
        
        private string TrackingCodeField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CurrencyName
        {
            get
            {
                return this.CurrencyNameField;
            }
            set
            {
                this.CurrencyNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerIBAN
        {
            get
            {
                return this.CustomerIBANField;
            }
            set
            {
                this.CustomerIBANField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DealDate
        {
            get
            {
                return this.DealDateField;
            }
            set
            {
                this.DealDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeName
        {
            get
            {
                return this.ExchangeNameField;
            }
            set
            {
                this.ExchangeNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ExchangeNationalId
        {
            get
            {
                return this.ExchangeNationalIdField;
            }
            set
            {
                this.ExchangeNationalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalId
        {
            get
            {
                return this.NationalIdField;
            }
            set
            {
                this.NationalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RialEqualityAmount
        {
            get
            {
                return this.RialEqualityAmountField;
            }
            set
            {
                this.RialEqualityAmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShId
        {
            get
            {
                return this.ShIdField;
            }
            set
            {
                this.ShIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string TrackingCode
        {
            get
            {
                return this.TrackingCodeField;
            }
            set
            {
                this.TrackingCodeField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealerInfo", Namespace="http://schemas.datacontract.org/2004/07/CBI.SANA.DataContracts.Bank")]
    public partial class DealerInfo : object
    {
        
        private string BirthDateField;
        
        private string FirstNameField;
        
        private string LastNameField;
        
        private string MobileNumberField;
        
        private string NationalIdField;
        
        private string ShIdField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NationalId
        {
            get
            {
                return this.NationalIdField;
            }
            set
            {
                this.NationalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ShId
        {
            get
            {
                return this.ShIdField;
            }
            set
            {
                this.ShIdField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SanaDealingInfo", Namespace="http://schemas.datacontract.org/2004/07/CBI.SANA.DataContracts.Bank")]
    public partial class SanaDealingInfo : object
    {
        
        private int AmountField;
        
        private int CurrencyCodeField;
        
        private int CurrencySourceField;
        
        private int CurrencyUseIdField;
        
        private System.DateTime DealDateField;
        
        private int ExchangeIdField;
        
        private string NakhodaTrackingCodeField;
        
        private int RateField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Amount
        {
            get
            {
                return this.AmountField;
            }
            set
            {
                this.AmountField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyCode
        {
            get
            {
                return this.CurrencyCodeField;
            }
            set
            {
                this.CurrencyCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencySource
        {
            get
            {
                return this.CurrencySourceField;
            }
            set
            {
                this.CurrencySourceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CurrencyUseId
        {
            get
            {
                return this.CurrencyUseIdField;
            }
            set
            {
                this.CurrencyUseIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DealDate
        {
            get
            {
                return this.DealDateField;
            }
            set
            {
                this.DealDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ExchangeId
        {
            get
            {
                return this.ExchangeIdField;
            }
            set
            {
                this.ExchangeIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NakhodaTrackingCode
        {
            get
            {
                return this.NakhodaTrackingCodeField;
            }
            set
            {
                this.NakhodaTrackingCodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Rate
        {
            get
            {
                return this.RateField;
            }
            set
            {
                this.RateField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="BankService.ISanaBankService")]
    public interface ISanaBankService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/GetSanaInfo", ReplyAction="http://tempuri.org/ISanaBankService/GetSanaInfoResponse")]
        BankService.SanaBankInfo GetSanaInfo(BankService.SanaRequestInfo sanaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/GetSanaInfo", ReplyAction="http://tempuri.org/ISanaBankService/GetSanaInfoResponse")]
        System.Threading.Tasks.Task<BankService.SanaBankInfo> GetSanaInfoAsync(BankService.SanaRequestInfo sanaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/CancelSanaTransaction", ReplyAction="http://tempuri.org/ISanaBankService/CancelSanaTransactionResponse")]
        int CancelSanaTransaction(BankService.SanaRequestInfo sanaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/CancelSanaTransaction", ReplyAction="http://tempuri.org/ISanaBankService/CancelSanaTransactionResponse")]
        System.Threading.Tasks.Task<int> CancelSanaTransactionAsync(BankService.SanaRequestInfo sanaRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/CheckCustomerBalanceForBank", ReplyAction="http://tempuri.org/ISanaBankService/CheckCustomerBalanceForBankResponse")]
        bool CheckCustomerBalanceForBank(string nationalId, int currencyUsedId, int currencyId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/CheckCustomerBalanceForBank", ReplyAction="http://tempuri.org/ISanaBankService/CheckCustomerBalanceForBankResponse")]
        System.Threading.Tasks.Task<bool> CheckCustomerBalanceForBankAsync(string nationalId, int currencyUsedId, int currencyId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/InsertSanaTransactionForBank", ReplyAction="http://tempuri.org/ISanaBankService/InsertSanaTransactionForBankResponse")]
        string InsertSanaTransactionForBank(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/InsertSanaTransactionForBank", ReplyAction="http://tempuri.org/ISanaBankService/InsertSanaTransactionForBankResponse")]
        System.Threading.Tasks.Task<string> InsertSanaTransactionForBankAsync(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/GetSanaTrackingCode", ReplyAction="http://tempuri.org/ISanaBankService/GetSanaTrackingCodeResponse")]
        string GetSanaTrackingCode(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISanaBankService/GetSanaTrackingCode", ReplyAction="http://tempuri.org/ISanaBankService/GetSanaTrackingCodeResponse")]
        System.Threading.Tasks.Task<string> GetSanaTrackingCodeAsync(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public interface ISanaBankServiceChannel : BankService.ISanaBankService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.1.0")]
    public partial class SanaBankServiceClient : System.ServiceModel.ClientBase<BankService.ISanaBankService>, BankService.ISanaBankService
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public SanaBankServiceClient() : 
                base(SanaBankServiceClient.GetDefaultBinding(), SanaBankServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.basicEndpoint.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanaBankServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(SanaBankServiceClient.GetBindingForEndpoint(endpointConfiguration), SanaBankServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanaBankServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(SanaBankServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanaBankServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(SanaBankServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public SanaBankServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public BankService.SanaBankInfo GetSanaInfo(BankService.SanaRequestInfo sanaRequest)
        {
            return base.Channel.GetSanaInfo(sanaRequest);
        }
        
        public System.Threading.Tasks.Task<BankService.SanaBankInfo> GetSanaInfoAsync(BankService.SanaRequestInfo sanaRequest)
        {
            return base.Channel.GetSanaInfoAsync(sanaRequest);
        }
        
        public int CancelSanaTransaction(BankService.SanaRequestInfo sanaRequest)
        {
            return base.Channel.CancelSanaTransaction(sanaRequest);
        }
        
        public System.Threading.Tasks.Task<int> CancelSanaTransactionAsync(BankService.SanaRequestInfo sanaRequest)
        {
            return base.Channel.CancelSanaTransactionAsync(sanaRequest);
        }
        
        public bool CheckCustomerBalanceForBank(string nationalId, int currencyUsedId, int currencyId, int amount)
        {
            return base.Channel.CheckCustomerBalanceForBank(nationalId, currencyUsedId, currencyId, amount);
        }
        
        public System.Threading.Tasks.Task<bool> CheckCustomerBalanceForBankAsync(string nationalId, int currencyUsedId, int currencyId, int amount)
        {
            return base.Channel.CheckCustomerBalanceForBankAsync(nationalId, currencyUsedId, currencyId, amount);
        }
        
        public string InsertSanaTransactionForBank(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo)
        {
            return base.Channel.InsertSanaTransactionForBank(buyer, dealingInfo);
        }
        
        public System.Threading.Tasks.Task<string> InsertSanaTransactionForBankAsync(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo)
        {
            return base.Channel.InsertSanaTransactionForBankAsync(buyer, dealingInfo);
        }
        
        public string GetSanaTrackingCode(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo)
        {
            return base.Channel.GetSanaTrackingCode(buyer, dealingInfo);
        }
        
        public System.Threading.Tasks.Task<string> GetSanaTrackingCodeAsync(BankService.DealerInfo buyer, BankService.SanaDealingInfo dealingInfo)
        {
            return base.Channel.GetSanaTrackingCodeAsync(buyer, dealingInfo);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicEndpoint))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.basicEndpoint))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8081/SanaBankService.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return SanaBankServiceClient.GetBindingForEndpoint(EndpointConfiguration.basicEndpoint);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return SanaBankServiceClient.GetEndpointAddress(EndpointConfiguration.basicEndpoint);
        }
        
        public enum EndpointConfiguration
        {
            
            basicEndpoint,
        }
    }
}
